A more robust teardown
Signed-off-by: Michael Steiner <michael.steiner@intel.com>

diff --git a/utils/docker/Makefile b/utils/docker/Makefile
--- a/utils/docker/Makefile
+++ b/utils/docker/Makefile
@@ -19,6 +19,7 @@ FPC_DOCKER_PEER_NAME = $(FPC_DOCKER_PEER_NAMESPACE)$(HW_EXTENSION)
 DOCKER_DAEMON_SOCKET ?= /var/run/docker.sock
 FABRIC_PEER_DAEMON_CHAINCODE_PORT ?= 7052
 
+DOCKER_DEV_CONTAINER_NAME = fpc-development-${FPC_VERSION}
 DOCKER_DEV_BUILD_OPTS ?=
 ifdef DOCKER_DEV_IMAGE_APT_ADD__PKGS
 	DOCKER_DEV_BUILD_OPTS += --build-arg APT_ADD_PKGS=$(DOCKER_DEV_IMAGE_APT_ADD__PKGS)
@@ -45,7 +46,11 @@ endif
 build: base ccenv cc-builder
 
 run: dev
-	$(DOCKER) run $(DOCKER_DEV_RUN_OPTS) -it $(FPC_DOCKER_NAMESPACE)-dev:${FPC_VERSION}
+	# Cleanup existing but non-running (note absence of --force in rm!) old dev containers
+	dev_container_id=$$(docker ps -a | grep ${DOCKER_DEV_CONTAINER_NAME} | awk '{ print $$1 }'); \
+	   [ -z  "$${dev_container_id}" ] || ${DOCKER} rm "$${dev_container_id}"
+	# Now run a new instance
+	$(DOCKER) run $(DOCKER_DEV_RUN_OPTS) --name ${DOCKER_DEV_CONTAINER_NAME} -it $(FPC_DOCKER_NAMESPACE)-dev:${FPC_VERSION}
 
 clobber:
 	# first clean-up dangling images as that might prevent some of the later cleans
@@ -71,8 +76,17 @@ clobber:
 		$(FPC_DOCKER_CCENV_NAME) \
 		$(FPC_DOCKER_BASE_NAME) \
 	    ; do \
-		if [ ! -z "$$(docker images -q $${img}:$${tag})" ]; then ${DOCKER} rmi $${img}:$${tag} || exit 1; fi \
-	done; \
+		if [ ! -z "$$(docker images -q $${img}:$${tag})" ]; then \
+		    ${DOCKER} rmi $${img}:$${tag}; \
+		    if [ $$? != 0 ]; then \
+			if [ "$${img}" = "$(FPC_DOCKER_DEV_NAME)" ]; then \
+			    echo 1>&2 "Could not remove dev container '$(FPC_DOCKER_DEV_NAME)', ignoring error"; \
+			else \
+			    exit 1; \
+			fi \
+		    fi \
+		fi \
+	    done \
 	done
 
 
