Concept Release (1.0) with versioned images & able out of the box to run demo (#339)
* Update rocket chat

We got our own rocket chat channel! Please join us at

Signed-off-by: bur <bur@zurich.ibm.com>

* fix environment

Signed-off-by: lengyijun <sjtu5140809011@gmail.com>

* fix README.md

Signed-off-by: lengyijun <sjtu5140809011@gmail.com>

* Bump acorn from 6.4.0 to 6.4.1 in /demo/client/frontend

Bumps [acorn](https://github.com/acornjs/acorn) from 6.4.0 to 6.4.1.
- [Release notes](https://github.com/acornjs/acorn/releases)
- [Commits](https://github.com/acornjs/acorn/compare/6.4.0...6.4.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump node deps

Update node deps in demo frontend/backend and docker utils

Signed-off-by: bur <bur@zurich.ibm.com>

* update CODEOWNERS (#263)

* update list

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

* fixup! update list

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

* disclaimer and explicit list of "official" releases

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

* make avatar download a bit more robust and graceful

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

* Docker dev run mounts FPC from local fs

This mounts the local FPC repository by default into a dev container
when `make run` is called. Before this was optional but turned out that
it should be the default.

Signed-off-by: bur <bur@zurich.ibm.com>

* Fix build for concept-release
- move both dev and peer to build from local HEAD commit
- (try to) minimize re-build of images
- add missing dependencies to dev container

Signed-off-by: michael steiner <michael.steiner@intel.com>

* Version docker images

Signed-off-by: michael steiner <michael.steiner@intel.com>

* Make FABRIC_VERSION arg/env in dockerfile consistent with vars used to get docker tag

Signed-off-by: michael steiner <michael.steiner@intel.com>

* More robust and precise handling of docker image cleanup

Signed-off-by: michael steiner <michael.steiner@intel.com>

* A more robust teardown

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

* Make missing device error more explicit and make SGX_MODE=SIM default for build
- note this is already done for a number of scripts and makes it more fail-safe
  from usage-perspective (though not from security :-). Also note that cmake still
  has a HW default but that will be removed and referring to the config.mk default
  in a separate PR)

Signed-off-by: michael steiner <michael.steiner@intel.com>

* Fix path so we can call make also via `make -C utils/docker run`

Signed-off-by: michael steiner <michael.steiner@intel.com>

* Make rm failure abort make (Note rm -f does _not_ file if the files do not exist ..)

Signed-off-by: michael steiner <michael.steiner@intel.com>

* Make docker-based tests run also inside dev(elopment) container
* make sure host network is also available inside
* for volume mounts, make sure the source path maps to a path
  understood by docker daemon

Signed-off-by: michael steiner <michael.steiner@intel.com>

* Build/Test only via dev container and not also directly on host

Signed-off-by: michael steiner <michael.steiner@intel.com>

Co-authored-by: bur <bur@zurich.ibm.com>
Co-authored-by: lyj <sjtu5140809011@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/utils/docker/Makefile b/utils/docker/Makefile
--- a/utils/docker/Makefile
+++ b/utils/docker/Makefile
@@ -19,20 +19,34 @@ FPC_DOCKER_PEER_NAME = $(FPC_DOCKER_PEER_NAMESPACE)$(HW_EXTENSION)
 DOCKER_DAEMON_SOCKET ?= /var/run/docker.sock
 FABRIC_PEER_DAEMON_CHAINCODE_PORT ?= 7052
 
+DOCKER_DEV_CONTAINER_NAME = fpc-development-${FPC_VERSION}
 DOCKER_DEV_BUILD_OPTS ?=
 ifdef DOCKER_DEV_IMAGE_APT_ADD__PKGS
 	DOCKER_DEV_BUILD_OPTS += --build-arg APT_ADD_PKGS=$(DOCKER_DEV_IMAGE_APT_ADD__PKGS)
 endif
 
+DOCKER_DEV_OPTIONAL_CMD= 
+
+DOCKER_GOPATH=/project
+DOCKER_FPC_PATH=$(DOCKER_GOPATH)/src/github.com/hyperledger-labs/fabric-private-chaincode
 
 DOCKER_DEV_RUN_OPTS ?=
-DOCKER_DEV_RUN_OPTS += -p $(FABRIC_PEER_DAEMON_CHAINCODE_PORT):$(FABRIC_PEER_DAEMON_CHAINCODE_PORT) -v $(DOCKER_DAEMON_SOCKET):$(DOCKER_DAEMON_SOCKET)
-DOCKER_GOPATH=/project
-DOKER_FPCPATH=$(DOCKER_GOPATH)/src/github.com/hyperledger-labs/fabric-private-chaincode
+# - import docker daemon socket (so dev container can run docker)
+DOCKER_DEV_RUN_OPTS += -v $(DOCKER_DAEMON_SOCKET):$(DOCKER_DAEMON_SOCKET)
+# - mount local fpc repo into the dev container so development inside container is
+#   persistant (and also can be done from outside with whatever favorite IDE ...)
+DOCKER_DEV_RUN_OPTS += -v "$(abspath ${TOP})":$(DOCKER_FPC_PATH)
+# - inject into dev containers environment the path of the hosts FPC_PATH to enable
+#   volume mounts inside the container
+DOCKER_DEV_RUN_OPTS += --env DOCKERD_FPC_PATH=$(FPC_PATH)/
+# - to make it possible to easily access docker-compose exposed ports accessible as localhost
+#   inside dev container as you would outside, we map the host network stack into the container
+DOCKER_DEV_RUN_OPTS += --net=host
+# - if sgx exists, pass also the corresponding device and aesmd socket to dev container
 SGX_DEVICE_PATH ?= $(shell if [ -e "/dev/isgx" ]; then echo "/dev/isgx"; elif [ -e "/dev/sgx" ]; then echo "/dev/sgx"; fi)
 SGX_PSW_SOCKET ?= /var/run/aesmd
 ifneq ($(SGX_DEVICE_PATH),)
-	DOCKER_DEV_RUN_OPTS += -v $(PWD)/../../config/ias/:$(DOKER_FPCPATH)/config/ias/ -v $(SGX_PSW_SOCKET):$(SGX_PSW_SOCKET) --device $(SGX_DEVICE_PATH)
+	DOCKER_DEV_RUN_OPTS += -v "$(DOCKERD_FPC_PATH)/config/ias/":$(DOCKER_FPC_PATH)/config/ias/ -v $(SGX_PSW_SOCKET):$(SGX_PSW_SOCKET) --device $(SGX_DEVICE_PATH)
 endif
 
 .PHONY: base ccenv dev peer cc-builder
@@ -42,7 +56,11 @@ endif
 build: base ccenv cc-builder
 
 run: dev
-	$(DOCKER) run $(DOCKER_DEV_RUN_OPTS) -it $(FPC_DOCKER_NAMESPACE)-dev
+	# Cleanup existing but non-running (note absence of --force in rm!) old dev containers
+	dev_container_id=$$(docker ps -a | grep ${DOCKER_DEV_CONTAINER_NAME} | awk '{ print $$1 }'); \
+	   [ -z  "$${dev_container_id}" ] || ${DOCKER} rm "$${dev_container_id}"
+	# Now run a new instance
+	$(DOCKER) run $(DOCKER_DEV_RUN_OPTS) --name ${DOCKER_DEV_CONTAINER_NAME} -it $(FPC_DOCKER_NAMESPACE)-dev:${FPC_VERSION} ${DOCKER_DEV_OPTIONAL_CMD}
 
 clobber:
 	# first clean-up dangling images as that might prevent some of the later cleans
@@ -50,17 +68,35 @@ clobber:
 	# then clean-up docker-compose network and demo related artifacts
 	(cd ../docker-compose; ${MAKE} clobber)
 	# delete locally created docker images and left-over peer artifacts
-	for imgs in \
+	for img in \
 		dev-* \
 		dev_test-* \
+	; do \
+		IMAGES=$$(${DOCKER} images $${img} -q); \
+		if [ ! -z "$${IMAGES}" ]; then ${DOCKER} rmi -f $${IMAGES} || exit 1; fi \
+	done; \
+	for tag in \
+	    ${FPC_VERSION} \
+	    latest \
+	; do \
+	    for img in \
 	        ${FPC_DOCKER_PEER_NAME} \
 		$(FPC_DOCKER_CC_BUILDER_NAME) \
 		$(FPC_DOCKER_DEV_NAME) \
 		$(FPC_DOCKER_CCENV_NAME) \
 		$(FPC_DOCKER_BASE_NAME) \
-	; do \
-		IMAGES=$$(${DOCKER} images $${imgs} -q); \
-		if [ ! -z "$${IMAGES}" ]; then ${DOCKER} rmi -f $${IMAGES} || exit 1; fi \
+	    ; do \
+		if [ ! -z "$$(docker images -q $${img}:$${tag})" ]; then \
+		    ${DOCKER} rmi $${img}:$${tag}; \
+		    if [ $$? != 0 ]; then \
+			if [ "$${img}" = "$(FPC_DOCKER_DEV_NAME)" ]; then \
+			    echo 1>&2 "Could not remove dev container '$(FPC_DOCKER_DEV_NAME)', ignoring error"; \
+			else \
+			    exit 1; \
+			fi \
+		    fi \
+		fi \
+	    done \
 	done
 
 
@@ -76,32 +112,48 @@ DOCKER_BUILD_OPTS ?=
 ifdef FORCE_REBUILD
 	DOCKER_BUILD_OPTS += --no-cache
 endif
+DOCKER_BUILD_OPTS += --build-arg FPC_VERSION=$(FPC_VERSION)
 
 
 base:
 	$(DOCKER) build $(DOCKER_BUILD_OPTS) -t $(FPC_DOCKER_BASE_NAME) base
+	$(DOCKER) tag $(FPC_DOCKER_BASE_NAME) $(FPC_DOCKER_BASE_NAME):${FPC_VERSION}
 
 ccenv: base
 	$(DOCKER) build $(DOCKER_BUILD_OPTS) -t $(FPC_DOCKER_CCENV_NAME) ccenv
+	$(DOCKER) tag $(FPC_DOCKER_CCENV_NAME) $(FPC_DOCKER_CCENV_NAME):${FPC_VERSION}
 
 # Note: for overall consistency reasons we want the FPC code from the current repo
 # as this will rebuild each time and take a while, we don't add a dependency
-# to the build target above ...
+# to the build target above for peer and dev ...
+# To enable docker to maximize build sharing between dev and peer
+# we add DOCKER_DEV_BUILD_OPTS (e.g., to get additional packages) also to peer
 peer: base
 	(cd ${TOP}; \
          $(DOCKER) build $(DOCKER_BUILD_OPTS) -t ${FPC_DOCKER_PEER_NAME}\
+         $(DOCKER_DEV_BUILD_OPTS)\
          -f utils/docker/peer/Dockerfile\
-         --build-arg FPC_REPO_URL=file:///tmp/build-src/.git\
-         --build-arg FPC_REPO_BRANCH=$$(git rev-parse --abbrev-ref HEAD)\
+         --build-arg FPC_REPO_URL=file:///tmp/cloned-local-fpc-git-repo\
+         --build-arg FPC_REPO_BRANCH_TAG_OR_COMMIT=$$(git rev-parse HEAD)\
          --build-arg SGX_MODE=${SGX_MODE}\
          . )
+	$(DOCKER) tag $(FPC_DOCKER_PEER_NAME) $(FPC_DOCKER_PEER_NAME):${FPC_VERSION}
 
 dev: base
-	$(DOCKER) build $(DOCKER_BUILD_OPTS) -t $(FPC_DOCKER_DEV_NAME) $(DOCKER_DEV_BUILD_OPTS) dev
+	(cd ${TOP}; \
+         $(DOCKER) build $(DOCKER_BUILD_OPTS) -t $(FPC_DOCKER_DEV_NAME)\
+         $(DOCKER_DEV_BUILD_OPTS)\
+         -f utils/docker/dev/Dockerfile\
+         --build-arg FPC_REPO_URL=file:///tmp/cloned-local-fpc-git-repo\
+         --build-arg FPC_REPO_BRANCH_TAG_OR_COMMIT=$$(git rev-parse HEAD)\
+         --build-arg SGX_MODE=${SGX_MODE}\
+         . )
+	$(DOCKER) tag $(FPC_DOCKER_DEV_NAME) $(FPC_DOCKER_DEV_NAME):${FPC_VERSION}
 
 cc-builder: dev
 	$(DOCKER) build $(DOCKER_BUILD_OPTS) \
 		-t $(FPC_DOCKER_CC_BUILDER_NAME)\
 		--build-arg SGX_MODE=${SGX_MODE}\
 		cc-builder
+	$(DOCKER) tag $(FPC_DOCKER_CC_BUILDER_NAME) $(FPC_DOCKER_CC_BUILDER_NAME):${FPC_VERSION}
 
