Fix for PR#73 and minor clean up (#75)
* check ercc container and force remove
* force remove in ecc_enclave
* ecc check container and image for stop/delete
* tlcc_enclave force rm files
* typo in tlcc mrenclave generate script
* fix sh complaint
* check container in ecc make docker
* fixes PR #73
* remove makefile variable; better error message

Signed-off-by: Bruno Vavala <bruno.vavala@intel.com>

diff --git a/ecc/Makefile b/ecc/Makefile
--- a/ecc/Makefile
+++ b/ecc/Makefile
@@ -6,14 +6,14 @@ TOP = ..
 include $(TOP)/build.mk
 
 LD_LIBRARY_PATH := LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:./enclave/lib
-PEER_NAME ?= dev-jdoe
 CC_NAME ?= ecc
 
 VSCC_SRC = vscc/ecc_validation_plugin.go vscc/ecc_validation_logic.go
 VSCC_OUT = ecc-vscc.so
 
-DOCKER_CONTAINER = $(PEER_NAME)-$(CC_NAME)-0
 DOCKER_IMAGE ?= $$(docker images | grep -- -$(CC_NAME)- | awk '{print $$1;}')
+DOCKER_CONTAINER_ID?=$$(docker ps | grep -- -$(CC_NAME)- | awk '{print $$1;}')
+
 
 #it seems that tests for ecc are broken;
 #TODO fix tests and include test target to all
@@ -25,7 +25,7 @@ ERR_MSG = "ecc_enclave build does not exist!"
 
 ecc_enclave:
 	@if [ ! -d $(ECC_ENCLAVE_BUILD)/lib ]; then echo $(ERR_MSG); exit 1; fi
-	@if [ ! -d $(ECC_ENCLAVE_BUILD)/include]; then echo $(ERR_MSG); exit 1; fi
+	@if [ ! -d $(ECC_ENCLAVE_BUILD)/include ]; then echo $(ERR_MSG); exit 1; fi
 
 ecc: ecc_enclave
 	$(GO) get golang.org/x/sync/semaphore
@@ -56,6 +56,11 @@ clean: docker-clean
 #	rm enclave/mrenclave.go
 
 docker:
+	@if [ -z "${DOCKER_IMAGE}" ]; then\
+		echo "\033[0;31mERROR: cannot override $(CC_NAME) docker image - not found\033[0m";\
+		exit 1;\
+	fi
+	echo "\033[1;33mWARNING: overriding $(CC_NAME) docker image\033[0m"
 	$(DOCKER) build -t $(DOCKER_IMAGE) -f Dockerfile ..
 
 docker-run:
@@ -63,7 +68,7 @@ docker-run:
 		-it \
 		--device /dev/isgx \
 		-v /var/run/aesmd:/var/run/aesmd \
-		--name $(DOCKER_CONTAINER) \
+		--name $(CC_NAME) \
 		-e "CORE_CHAINCODE_LOGGING_LEVEL=DEBUG" \
 		-e "CORE_CHAINCODE_LOGGING_SHIM=INFO" \
 		-e "CORE_PEER_ADDRESS=172.17.0.1:7051" \
@@ -72,9 +77,9 @@ docker-run:
 		chaincode
 
 docker-stop:
-	-docker stop $(DOCKER_CONTAINER)
-	-docker rm $(DOCKER_CONTAINER)
+	-if [ ! -z "$(DOCKER_CONTAINER_ID)" ]; then docker stop $(DOCKER_CONTAINER_ID); fi
+	-if [ ! -z "$(DOCKER_CONTAINER_ID)" ]; then docker rm $(DOCKER_CONTAINER_ID); fi
 
 docker-clean: docker-stop
-	-docker rmi $(DOCKER_IMAGE)
+	-if [ ! -z "$(DOCKER_IMAGE)" ]; then docker rmi -f $(DOCKER_IMAGE); fi
 
